version: '3.8'
services:
  ollama:
    build:
      context: .
      dockerfile: docker/ollama/Dockerfile.app
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    environment:
      OLLAMA_MODELS: /root/.ollama/models
    

  gradio:
    build:
      context: .
      dockerfile: docker/gradio/Dockerfile.app
    ports:
      - "7860:7860"
    depends_on:
      - ollama
    environment:
      OLLAMA_URL:  "http://ollama:11434" # Replace with the actual URL/port if needed
      JINJA_TEMPLATE_PATH:  /app/templates/rag_query_pixegami.txt 
      EMBEDDER_MODEL: nomic-embed-text # Make sure these are consistent with the ones listed in ollama_init.sh
      GENERATOR_MODEL: mistral
volumes:
  ollama:
